name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: |-
        GOOS=linux   GOARCH=amd64 go build -o release/linux/amd64/gitness-cli ./gitness
        GOOS=linux   GOARCH=arm64 go build -o release/linux/arm64/gitness-cli ./gitness
        GOOS=darwin  GOARCH=amd64 go build -o release/darwin/amd64/gitness-cli ./gitness
        GOOS=darwin  GOARCH=arm64 go build -o release/darwin/arm64/gitness-cli ./gitness

    - name: Archive
      run: |-
        tar -cvzf release/gitness-cli-linux-amd64.tar.gz   -C release/linux/amd64   gitness-cli
        tar -cvzf release/gitness-cli-linux-arm64.tar.gz   -C release/linux/arm64   gitness-cli
        tar -cvzf release/gitness-cli-darwin-amd64.tar.gz  -C release/darwin/amd64  gitness-cli
        tar -cvzf release/gitness-cli-darwin-arm64.tar.gz  -C release/darwin/arm64  gitness-cli
